# Generated by Django 6.0.6 on 2026-08-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('organization_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('designation', models.CharField(choices=[('', 'Select Specific Role'), ('professor', 'Professor'), ('trainer', 'Trainer'), ('admin', 'Administrator')], max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
